"""add sent_reminders table

Revision ID: 283a6cd95b42
Revises: bbd9f3f79a08
Create Date: 2026-10-01 11:02:29.721840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283a6cd95b42'
down_revision: Union[str, None] = 'bbd9f3f79a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reminder_type', 'entity_id', name='uq_sent_reminder')
    )
    op.create_index(op.f('ix_sent_reminders_id'), 'sent_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_sent_reminders_user_id'), 'sent_reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_reminders_user_id'), table_name='sent_reminders')
    op.drop_index(op.f('ix_sent_reminders_id'), table_name='sent_reminders')
    op.drop_table('sent_reminders')
    # ### end Alembic commands ###