"""add indexes on FK columns

Revision ID: bbd9f3f79a08
Revises: 4ff75d9f7c8e
Create Date: 2026-10-01 10:10:23.956590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd9f3f79a08'
down_revision: Union[str, None] = '4ff75d9f7c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_index(op.f('ix_assignments_group_id'), 'assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_assignments_student_id'), 'assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_assignments_teacher_id'), 'assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_chats_assignment_id'), 'chats', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_chats_student_id'), 'chats', ['student_id'], unique=False)
    op.create_index(op.f('ix_chats_teacher_id'), 'chats', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_folder_access_folder_id'), 'folder_access', ['folder_id'], unique=False)
    op.create_index(op.f('ix_folder_access_student_id'), 'folder_access', ['student_id'], unique=False)
    op.create_index(op.f('ix_group_students_group_id'), 'group_students', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_students_student_id'), 'group_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_groups_teacher_id'), 'groups', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_invitations_teacher_id'), 'invitations', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lesson_requests_start_time'), 'lesson_requests', ['start_time'], unique=False)
    op.create_index(op.f('ix_lesson_requests_status'), 'lesson_requests', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_requests_student_id'), 'lesson_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_lesson_requests_teacher_id'), 'lesson_requests', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lessons_start_time'), 'lessons', ['start_time'], unique=False)
    op.create_index(op.f('ix_lessons_student_id'), 'lessons', ['student_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_material_folders_teacher_id'), 'material_folders', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_materials_folder_id'), 'materials', ['folder_id'], unique=False)
    op.create_index(op.f('ix_materials_teacher_id'), 'materials', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_index(op.f('ix_payments_teacher_id'), 'payments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_index(op.f('ix_reviews_lesson_id'), 'reviews', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_reviews_student_id'), 'reviews', ['student_id'], unique=False)
    op.create_index(op.f('ix_reviews_tutor_id'), 'reviews', ['tutor_id'], unique=False)
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_tests_group_id'), 'tests', ['group_id'], unique=False)
    op.create_index(op.f('ix_tests_student_id'), 'tests', ['student_id'], unique=False)
    op.create_index(op.f('ix_tests_teacher_id'), 'tests', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_test_id'), 'user_answers', ['user_test_id'], unique=False)
    op.create_index(op.f('ix_user_tests_test_id'), 'user_tests', ['test_id'], unique=False)
    op.create_index(op.f('ix_user_tests_user_id'), 'user_tests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tests_user_id'), table_name='user_tests')
    op.drop_index(op.f('ix_user_tests_test_id'), table_name='user_tests')
    op.drop_index(op.f('ix_user_answers_user_test_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_index(op.f('ix_tests_teacher_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_student_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_group_id'), table_name='tests')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_index(op.f('ix_reviews_tutor_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_student_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_lesson_id'), table_name='reviews')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_payments_teacher_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_materials_teacher_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_folder_id'), table_name='materials')
    op.drop_index(op.f('ix_material_folders_teacher_id'), table_name='material_folders')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_student_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_start_time'), table_name='lessons')
    op.drop_index(op.f('ix_lesson_requests_teacher_id'), table_name='lesson_requests')
    op.drop_index(op.f('ix_lesson_requests_student_id'), table_name='lesson_requests')
    op.drop_index(op.f('ix_lesson_requests_status'), table_name='lesson_requests')
    op.drop_index(op.f('ix_lesson_requests_start_time'), table_name='lesson_requests')
    op.drop_index(op.f('ix_invitations_teacher_id'), table_name='invitations')
    op.drop_index(op.f('ix_groups_teacher_id'), table_name='groups')
    op.drop_index(op.f('ix_group_students_student_id'), table_name='group_students')
    op.drop_index(op.f('ix_group_students_group_id'), table_name='group_students')
    op.drop_index(op.f('ix_folder_access_student_id'), table_name='folder_access')
    op.drop_index(op.f('ix_folder_access_folder_id'), table_name='folder_access')
    op.drop_index(op.f('ix_chats_teacher_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_student_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_assignment_id'), table_name='chats')
    op.drop_index(op.f('ix_assignments_teacher_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_student_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_group_id'), table_name='assignments')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    # ### end Alembic commands ###