"""add unique constraints

Revision ID: f1abb6597b1e
Revises: 283a6cd95b42
Create Date: 2026-10-01 11:52:06.284514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1abb6597b1e'
down_revision: Union[str, None] = '283a6cd95b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_folder_access', 'folder_access', ['folder_id', 'student_id'])
    op.create_unique_constraint('uq_group_student', 'group_students', ['group_id', 'student_id'])
    op.create_unique_constraint('uq_review_tutor_student', 'reviews', ['tutor_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_tutor_student', 'reviews', type_='unique')
    op.drop_constraint('uq_group_student', 'group_students', type_='unique')
    op.drop_constraint('uq_folder_access', 'folder_access', type_='unique')
    # ### end Alembic commands ###